### ISSUE TITLE
Request: data-driven tempt/tame/breed items

### ISSUE THREAD

**Issue by katubug** [ginerJ/Tameable-Beasts#3]
Hello! I'm a modpack maker and I'm adding this mod into one of my upcoming packs. One thing that I would really love is for the ability to define via tags what items tempt, tame, and breed the creatures in the mod, so that I can easily add mod compatibility. Additionally, as I usually run servers for my modpacks, I don't want players to have to run around killing the large bird mounts to get the meat to tame the opposing bird mount. I also tend to go for kind of a cozy vibe, so I want to stick to the idea that the animals in the mod are friends, not food. xD

Would this be something you'd be willing to implement? Thank you very much for your time, and for the excellent mod!

**Comment by ginerJ** [comment]
![image](https://github.com/user-attachments/assets/aa32be6b-04dc-4fc9-9c83-e4b6604dabbf)
Totally agree, will make this a feature in the very close next update, thanks for the feedback!

**Comment by ginerJ** [comment]
dropped the next update
